server:
  port: 9321


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.138.135/dbgirl
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
