server:
  port: 9321


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.75.134/dbgirl
    username: root
    password: abc123456
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
